-- Adds catalogue/certificate/datasheet document links (Google Drive) for products seeded in V7, crawled from each product's page on https://postef.com.vn/san-pham/. Not every product has documents; only the products listed below had any linked on their page.

INSERT INTO schema_migrations (version) VALUES ('V8__seed_postef_product_catalogues__ndat2003');

INSERT INTO productcatalogues (product_id, catalogue_url, file_name, display_order) VALUES
((SELECT product_id FROM products WHERE product_code = 'SP-0001'), 'https://drive.google.com/file/d/1lAoND44iEzSuLYnXEj7DfHNGJfHMDcBD/view?usp=sharing', 'PDA10-48100', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0001'), 'https://drive.google.com/file/d/1RlG8INwBZt2GvJmxACADsWrJqRIR4ls8/view?usp=sharing', 'PDA10-4850', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0002'), 'https://drive.google.com/file/d/1VS_AqCiMar1uW4BTrAL8-wQfyIDKDnU5/view?usp=drive_link', 'Ắc quy lưu động POSLI02/48100', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0003'), 'https://drive.google.com/file/d/1Yr92GHQZDVtgFgj76BTWXKZyQL2ymJRk/view', 'PNGB 2V300Ah', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0003'), 'https://drive.google.com/file/d/1Dly99Oenz0R_J5OvXeyjEUDX5UTxdyEt/view', 'PNGB 2V500Ah', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0004'), 'https://drive.google.com/file/d/1pFcVvENaOVtUnq4QsyAe3SHdr63ilu90/view?usp=sharing', 'PNGB 12V150Ah', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0004'), 'https://drive.google.com/file/d/1_mtLp49QFmI1YcM6UsszwDxdfaft2kpA/view?usp=sharing', 'PNGB 12V200Ah', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0006'), 'https://drive.google.com/file/d/1biMagOTzQ60W1Xq4evBYjFKNgVwinFRV/view?usp=sharing', 'POSTEF_ZXD3000 Rectifier', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0006'), 'https://drive.google.com/file/d/1lGGdDSP6J6s3zCWfT41W2oq2b3k6SiBp/view?usp=sharing', 'POSTEF_ZXDU CSU501B Centralized Supervision Unit', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0006'), 'https://drive.google.com/file/d/1r4lfJTRMXigVIRs2G6mhj3CFrmVEH662/view?usp=sharing', 'POSTEF_ZXDU68 B301 Embedded DC power system', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0007'), 'https://drive.google.com/file/d/1y7u4a8Py4MM3IFdvMvzrArLBhALW3nYa/view', 'UNIPOWER GDN.S.48.M24 & GDN.S.48.MS32', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0007'), 'https://drive.google.com/file/d/1Jc99OZBRx0CyA_Tc-xcjzq31dJJqQuK0/view', 'UNIPOWER GDN.S.48.MS31', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0007'), 'https://drive.google.com/file/d/1GW7GSMMjz4z7j4P_zcpKtJhP9E08qfXi/view', 'UNIPOWER MODEL GDN.S.48.M27', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0007'), 'https://drive.google.com/file/d/1hYl-4BObhatjlhW2NpmqSKedIxUF6F2W/view', 'UNIPOWER GDN.S.48.M26 & GDN.S.48.MS31', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0008'), 'https://drive.google.com/file/d/1OgpXsM5P3CVOgYCAQ4K3bw8sHdZ5BELz/view', 'EATON UPS 9395', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0009'), 'https://drive.google.com/file/d/1EhMcoCoHcjQ9GNvSacHQOazlx92oNezE/view', 'POS-HES ESP6_72_300-320 45mm', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0009'), 'https://drive.google.com/file/d/1DG09yTySNm7y332t9eo4MsD4X9Z2wizi/view', 'Bộ điều khiển TriStar-60A', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0010'), 'https://drive.google.com/file/d/1z8Z14okLiY3zGNUbNOlug79YqZY3V8J8/view?usp=sharing', 'CÁP QUANG ADSS 48FO- KV 400M', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0011'), 'https://drive.google.com/file/d/15oBoLWVYcxAIa15fk4cUP593h6lTGnDb/view', 'Chỉ tiêu kỹ thuật - LLDPE 1FO/2FO/4FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0011'), 'https://drive.google.com/file/d/12tWS4OIDnFMCPRmZ_tvJ5MVRnIcGftY9/view?usp=sharing', 'Chỉ tiêu kỹ thuật - LSZH 1FO', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/15Bx3DBkuJ4bcNtWhZKNHQkklRbo9Yeac/view', 'CÁP CỐNG KL 6-24FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/1GhLWaoODLTgc6ig9XUNyPZ8lKxkKNmS9/view', 'CÁP CỐNG KL 48FO', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/1vFRWMLIw-KrhQnCTUSyAf6K8CmbwaeWb/view', 'CÁP CỐNG KL 6-96FO', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/14QU27mLF3s3_CvwrR6RCL2C5Zh2ArKA1/view?usp=drive_link', 'CÁP QUANG 8-96FO', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/1-0WjNDaloLcE8Hs7JUPUv4y6EQczjhwa/view?usp=drive_link', 'CÁP QUANG CHÔN TRỰC TIẾP 12FO 2 LỚP VỎ', 4),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/11gLnE9dmD7UnmcsO4fFnrOyLNIFuJIZI/view?usp=drive_link', 'CÁP QUANG CHÔN TRỰC TIẾP 48FO 2 LỚP VỎ', 5),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/1uzFFb6nkfpDx9BJBRa5aUDHKl2W_4sJo/view?usp=drive_link', 'CÁP QUANG CHÔN TRỰC TIẾP 96FO 2 LỚP VỎ', 6),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/11OTNFAJHrvnzD1hZoQcI31RmS_xSkDwR/view?usp=drive_link', 'DÂY THUÊ BAO KÉO CỐNG 2FO', 7),
((SELECT product_id FROM products WHERE product_code = 'SP-0012'), 'https://drive.google.com/file/d/1lFsHEDtxiAF-ur64KwndHCpkhAkSAR5a/view?usp=drive_link', 'TCKT CQ CÁC LOẠI CQ MIDSPAN', 8),
((SELECT product_id FROM products WHERE product_code = 'SP-0013'), 'https://drive.google.com/file/d/1zPA6uDuqDlWS7WTWu7UUYlbC9pw6GjyX/view', 'CÁP QUANG TREO 6-96FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0013'), 'https://drive.google.com/file/d/1wTP1Oo2ciwjf-BDizegWA0If8JTaZKMg/view', 'CÁP QUANG TREO PKL 8FO', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0013'), 'https://drive.google.com/file/d/1Ql4WGZXcv9_VvnZn0IlvCMnNoNQnvuaO/view?usp=sharing', 'CÁP QUANG TREO PKL 12/24/48/96FO', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0013'), 'https://drive.google.com/file/d/1UOkENPwvQMxZikHRSKXC0G0-RCaPdMrw/view?usp=drive_link', 'TCKT CQ CÁC LOẠI', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0014'), 'https://drive.google.com/file/d/1_ws98BghE3OgRhaqZzWYztCgltwvsG5w/view?usp=drive_link', 'DÂY THUÊ BAO LSZH 1FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0015'), 'https://drive.google.com/file/d/1KlaclsaXPg4FFmEu134Cpr-aWHyxqB7U/view', 'DÂY THUÊ BAO QUANG ĐỆM LỎNG (1FO/2FO/4FO)', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0015'), 'https://drive.google.com/file/d/1PK6QTB80EKT-IcmatEeevucksIzlUS3a/view?usp=drive_link', 'DÂY THUÊ BAO QUANG ĐỆM LỎNG 2FO/4FO', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0017'), 'https://drive.google.com/file/d/11VxyPNVXLR5YLShyvVj2bIaCDCdUVgl4/view', 'HỘP PHỐI QUANG 4FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0017'), 'https://drive.google.com/file/d/1XyNQRmczj6uvO-Id98a_RPMkVUIC52ag/view?usp=sharing', 'TỦ (HỘP) THUÊ BAO QUANG 16 CỔNG VỎ NHỰA (POS-SPL-16P/POS-HOS-16P)', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0017'), 'https://drive.google.com/file/d/1TKrC8C62NRSqKQxrkpYZF1k-hmWGavsY/view?usp=drive_link', 'TM KT HỘP PHỐI QUANG VỎ NHỰA', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0018'), 'https://drive.google.com/file/d/1tqhIyHunsrBLvWT0Ub1qVdNieqbh9wwY/view?usp=sharing', 'SPEC Hộp phân phối quang OTB 12-24FO, 48-96 FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0018'), 'https://drive.google.com/file/d/1k6n8pfZzovq_5CIcki8_e6KhgOnVZdOS/view?usp=drive_link', 'Thuyết minh kỹ thuật hộp phân phối quang tích hợp Splitter', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0018'), 'https://drive.google.com/file/d/1YVvkNA5vTjtq524T8yY9RpVoEFuijxAw/view?usp=drive_link', 'Thuyết minh kỹ thuật hộp phân phối quang hộp OTB', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0019'), 'https://drive.google.com/file/d/16STNeS05dN8dO5EVGAK57qD3cFFzfl3e/view?usp=drive_link', 'Tủ đấu nối quang 192FO đặt bệ', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0020'), 'https://drive.google.com/file/d/1Mj2l9NRlMID0GMjkY8SvfPBlmmWoVHVh/view', 'TỦ PHÂN PHỐI QUANG 144-288 FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0021'), 'https://drive.google.com/file/d/1sE1tVZYWxPH4YZQg-9zgWiGYVkru5DRm/view', 'Tủ đấu nối POS-EO-24SC', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0022'), 'https://drive.google.com/file/d/1IxcSgyg5rlVZiyvqmIDosx1B1hzCIHR8/view', 'TÀI LIỆU KTH KHUNG NẮP HẦM CÁP', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0023'), 'https://drive.google.com/file/d/1LUylTkvNc9h9VfppmMUIjDd0rhOKIype/view?usp=drive_link', 'TMKT Măng xông 12-24', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0023'), 'https://drive.google.com/file/d/1V6q3-J-5RPETGPPcHvVBBVOfigEcOovG/view?usp=drive_link', 'Catalogue MX 12-24', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0023'), 'https://drive.google.com/file/d/1lMT4j21DjbyTVuaWQ3rab2CpAkah4j6p/view?usp=drive_link', 'Catalogue MX 48-96', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0023'), 'https://drive.google.com/file/d/1J_xV0ForIFpt-BS_zAsCyOy8zAsn2pCg/view?usp=drive_link', 'Catalogue MXQ 96FO', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0024'), 'https://drive.google.com/file/d/164DhRqyFdMtFQX7xkGb1ix1W3LGw-kGp/view', 'ODF POT 12-96FO', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0024'), 'https://drive.google.com/file/d/1R7D5OQAxr2LWZNhYUcGIyB5UfVmOpeeT/view', 'ODF ĐẤU NỐI QUANG INDOOR LOẠI TRƯỢT', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0025'), 'https://drive.google.com/file/d/10gP-6wC4zzzJwG17ofgICPT3eyqTnW9o/view?usp=drive_link', 'TAI LIEU KY THUAT ONG NHUA PVC-U, PVC-HI VÀ PK', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1VwlqDoxbRCy84PH-0G5OeCqytvgKLVl9/view', 'FAST CONNECTOR FPK - SC/xxx-sss', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1OllHxa8pxjaSVoLUZAfbC_qn_D3QXgLg/view', 'TAI LIEU MODULE 12-24FO', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1QjMBpKEjg_zl46wckxetviJgfrwP-Av-/view?usp=sharing', 'BỘ CHIA QUANG PLC', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1gOAxP6FSXW0Pe5WovBYPapNo3KpjbZcn/view?usp=drive_link', 'CATALOGUE DÂY NỐI - DÂY NHẢY - ADAPTER', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1LRg_oql35HUhI-GmR6x1jX_U4EjDGMjC/view?usp=sharing', 'TMKT SPL RỜI', 4),
((SELECT product_id FROM products WHERE product_code = 'SP-0026'), 'https://drive.google.com/file/d/1CzokGQH5o13VBFmUxA0bJnXUwasSPlgh/view?usp=drive_link', 'KHAY HÀN TRÒN 24FO VA KHAY Hàn ETS 12FO', 5),
((SELECT product_id FROM products WHERE product_code = 'SP-0027'), 'https://drive.google.com/file/d/12ZRSSs8XvQkv9vVngOTZ4hbcSpZT87ju/view', 'XDWL-17-65V-VT', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0027'), 'https://drive.google.com/file/d/1grYbno3rwHVL6IfCror2iicsni2t8wOK/view', 'XQLHHH-16(17)-65V-iVT', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0027'), 'https://drive.google.com/file/d/146M1k143y-Y4HeMx-NU0k94Vz9eJMsEU/view', 'XXDWH-17-65V-VT-DM-R2', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0027'), 'https://drive.google.com/file/d/1yod1aLTu_nLYf2fodUoJsRKT_HsrKuxJ/view', 'XXXDWH-17-65V-iVT', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0028'), 'https://drive.google.com/file/d/1BnQl3FgUKhuTJAG89XiEYURbOdAcvNOK/view', 'ANTENA 4G POS_1710_2690', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0028'), 'https://drive.google.com/file/d/1jy3SXrO8n_Us1LBpi-HDuhath_RCxcVc/view', 'ANTENA 4G POS_1710_2170', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0028'), 'https://drive.google.com/file/d/1CJoEAWz1LaKpthqnHeda86kvjsFs1K2Z/view', 'ANTENA NGỤY TRANG', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0032'), 'https://drive.google.com/file/d/1awaYaVDtEPFU6c8cazNMH39BmIPiP1VU/view?usp=drive_link', 'Catalogue Tủ phân phối nguồn_PODSVN_MB02', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0032'), 'https://drive.google.com/file/d/1atrM_GLJju5-g3DF9CKRpDVctPh8lxLx/view?usp=drive_link', 'CSU501B Centralized Supervision Unit PD', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0032'), 'https://drive.google.com/file/d/1NzjNx6nWlfoZGhu251pbmrKcQTIr0ORI/view?usp=drive_link', 'ZXD3000 Rectifier Datasheet', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0033'), 'https://drive.google.com/file/d/1pLoJMyAULGihBw0VbPsXtyNe5OG1XQGi/view?usp=sharing', 'Thuyết minh kỹ thuật tủ lắp thiết bị ngoài trời PODS VN', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0033'), 'https://drive.google.com/file/d/1xjGX9ksIT3jkI4iXUcmRPCx_3hvgKM-B/view?usp=sharing', 'Catalogue tủ lắp thiết bị ngoài trời PODS VN', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0033'), 'https://drive.google.com/file/d/1AqGzh_5ZIoO2oB68SS31FVXm1xxQXcb-/view?usp=sharing', 'POSTEF_ZXDU68 B301 Embedded DC power system', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0033'), 'https://drive.google.com/file/d/1WINktz8y6hw8nKe9Tb5nwSDIhEkRjrEg/view?usp=sharing', 'POSTEF_ZXD3000 Rectifier', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0033'), 'https://drive.google.com/file/d/1U1Qui0awzKdemjDvg2mJDRS3bY-ljf0g/view?usp=sharing', 'POSTEF_ZXDU CSU501B Centralized Supervision Unit', 4),
((SELECT product_id FROM products WHERE product_code = 'SP-0034'), 'https://drive.google.com/file/d/1hjSu26EcyprRXd0f61oHpnrn6rMmx09o/view?usp=sharing', 'Tủ nguồn PODS VN-M02', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0034'), 'https://drive.google.com/file/d/13xJYcvOMkmKPv1my8WshbrzwQrvvq2Ap/view?usp=sharing', 'ZXDU68 B301 Embedded DC Power System Datasheet_241106PG', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0034'), 'https://drive.google.com/file/d/1RWbLx3pWFib4rFH7MgGmRkWJ_2ffoSKQ/view?usp=sharing', 'CSU501B Centralized Supervision Unit PD_241106PG', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0034'), 'https://drive.google.com/file/d/1US7d-zZojh29csm4KiO9z4ZsAx3wH9g-/view?usp=sharing', 'ZXD3000 Rectifier Datasheet_241106PG', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0035'), 'https://drive.google.com/file/d/144i4Bx9hjMo5ajQPO2yCNP0WNMfyXMJC/view', 'TỦ PP/RRU', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0036'), 'https://drive.google.com/file/d/1WtlfMVgV8AHEichFSZX_gjQSsowSV0DW/view', 'TỦ NGUỒN PS 60/15', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0037'), 'https://drive.google.com/file/d/1HAw_y6PcXgsiV5jiybSICJzPSZZeT0Se/view?usp=drive_link', 'Thuyết minh kỹ thuật ZXDU98 T601', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0037'), 'https://drive.google.com/file/d/1MgyfFOzBv_6-QqWJKaLMnRLRQD_-JMne/view?usp=drive_link', 'ZXDU98 T601 V6.0 Datasheet', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0037'), 'https://drive.google.com/file/d/1ssyQdqJ0HQ4-p_ScVbAbR4r3WfXmEz4j/view?usp=drive_link', 'ZXEPS R4850F1 Rectifier Datasheet', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0038'), 'https://drive.google.com/file/d/1fd5BUK41oxlA39iDBpVI9XlOmo-uZ82u/view', 'TỦ PHÂN PHỐI DB1', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1g-CgfKa1UzSz1kRFr6L9p2a1nBGkKruD/view', 'Tủ nguồn PP-AC-600A', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1X_3srKvAxNv_nLjoZlwWUIUk5Xz5etBy/view', 'Tủ nguồn PP-DC-600A', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1wcsv86cTfgPeF9JYjGZOAIlyPdqGj_32/view', 'Tủ phân phối PP-DC/1000', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1I7iP26rCc-6IT2ilAs8nbnffnHl1dSPQ/view', 'Tủ phân phối PP-DC/1200', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1t1yDLE3ZOQcAgspdUpw37sdBmjlGTz9T/view?usp=sharing', 'Thuyết minh kỹ thuật nguồn ZXDU68 T601', 4),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1rx_gHcYeJ2NPrQC9thV0sKYDxqANJrYa/view?usp=drive_link', 'Thuyet minh kỹ thuật tủ Phân phối DC PP - DC1500 final', 5),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/15IIWdSRzI8yUkQNTQBC1JnCJ8wFhlW9E/view?usp=drive_link', 'POSTEF_ZXDU68 B301 Embedded DC power system', 6),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1vS0ZdPQ8sL-TKVyXjyRqLaDHu0fVeVT7/view?usp=drive_link', 'POSTEF_ZXD3000 Rectifier', 7),
((SELECT product_id FROM products WHERE product_code = 'SP-0039'), 'https://drive.google.com/file/d/1EGoLL9Ua8KXJxxwpvLUH9AeypZw6mB6V/view?usp=drive_link', 'POSTEF_ZXDU CSU501B Centralized Supervision Unit', 8),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1RmPkn3lXB6aITE6z_bHk7klyP_st3NZ6/view', 'CẮT LỌC SÉT IPS34-200-200A (HỘP)', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1LSPzslucoAaDlE4PK57_wA29cz4gHfce/view', 'CẮT LỌC SÉT LPS 12 63 130 TSGTDS _LCD', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1vaJN0DYLUqgYEEs4YcPZjz4xvnb7OU0h/view', 'MODULE CẮT SÉT POT_SSDDC48- 40kA', 2),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1cFqMwN8MDdskB6rOASZiHIgrFGSHOTbx/view', 'SSD 34-200kA', 3),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1hangZqWcNrdqcf-9GQicRTiIs3qkUIsl/view', 'THIẾT BỊ CHỐNG SÉT AC POT-DT40-300-4V-S', 4),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1ur3j9oakXIr40mKAkncuyZjpaeSYj0wr/view', 'AC LIGHTNING BOX CLS - 3P', 5),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1c0GxTuOAd0NbNc2i75CaMG4MraLYZIwM/view', 'SSD 34-100kATDS', 6),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1WTbHB0PfOthSBXw-OTKbI6yeuzzMn0AB/view', 'SSD 12-100kATDS', 7),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1mGLKCCZn_JhLRgB_vXZNDZFFj1Ce5Tc4/view', 'Module cắt sét MOV DT 40KA320', 8),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1OlGOIhShL1OuwT2e2j-gQDP3tX8z1NCw/view?usp=drive_link', 'Catalog SPD FV25B-3 NPE-255S', 9),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1TdDIjr5uMGDGVlFaxIFMu43FyTWcgrKf/view?usp=drive_link', 'Catalog SPD FV25B-1 NPE-255S', 10),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1ETDeX5hQT0iePCLxVNj1gYULRMnpL9fM/view?usp=drive_link', 'Catalog SPD -DC POS2H-PV', 11),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1WKPaNFrufM3mceaXmSFJu4d5mTz_-PD1/view?usp=drive_link', 'Catalogue LPS 34-63-200kA', 12),
((SELECT product_id FROM products WHERE product_code = 'SP-0040'), 'https://drive.google.com/file/d/1-BSmS0lsGOaXlX5kKQuYvCNA9asXxEYc/view?usp=drive_link', 'Catalogue LPS 12-63A-200kA', 13),
((SELECT product_id FROM products WHERE product_code = 'SP-0047'), 'https://drive.google.com/file/d/13Krz3LAr1VafB955IbfDCClOz35g1IHl/view?usp=sharing', 'Chứng nhận hợp quy Raisecom_M6511', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0047'), 'https://drive.google.com/file/d/11eKerDBF_WyB9DjVJo7f5E0O8_OGSjTI/view?usp=sharing', 'Catalogue_Raisecom M6511', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0048'), 'https://drive.google.com/file/d/1bqTX-r-RS4gd_QleUSvem6Y-dqJ7S9GN/view?usp=sharing', 'Chứng nhận hợp quy Raisecom T189', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0048'), 'https://drive.google.com/file/d/1i4XO6Xot-thM9ICTrKp4NHDUgOM0pRbh/view?usp=sharing', 'Catalogue Raisecom T189', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0049'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0050'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0051'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0052'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0053'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0054'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0055'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0056'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0057'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0058'), 'https://drive.google.com/file/d/1N_8q_5miTtFhiEiox_6A0tGofEcSIFyR/view?usp=sharing', 'Hisense MIFI CPE for 5G', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0059'), 'https://drive.google.com/file/d/1YBS9q83voFV5OhEB7KZCE_O6s5Yip6yX/view?usp=sharing', 'POT-TMS_HỆ THỐNG QUẢN LÝ CÁC TRẠM VIỄN THÔNG', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0059'), 'https://drive.google.com/file/d/1JsvSvxBctOo5ZvMFQbkZWAx7ZjC3uwwx/view?usp=drive_link', 'Giới thiệu POT-TMS', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0060'), 'https://drive.google.com/file/d/13a8lSffCPyGKz5-FE8iNvMwSnnbjahiM/view?usp=sharing', 'Giới thiệu POT-TMSG', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0060'), 'https://drive.google.com/file/d/1JsvSvxBctOo5ZvMFQbkZWAx7ZjC3uwwx/view?usp=drive_link', 'Giới thiệu POT-TMS', 1),
((SELECT product_id FROM products WHERE product_code = 'SP-0080'), 'https://drive.google.com/file/d/1DcWieftxEsnn8WQNrxUo-Mk-MBpdGOxd/view?usp=sharing', 'HBR7305H datasheet', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0081'), 'https://drive.google.com/file/d/1O0WcYXfD_1UgvI4c8FbbGwivOKOSQ79h/view?usp=sharing', 'Hệ thống giám sát phòng Lap_Datassure', 0),
((SELECT product_id FROM products WHERE product_code = 'SP-0087'), 'https://drive.google.com/file/d/1cJG8Qj7q6eCLyKfoiI5lSKwcu13wjSKa/view?usp=sharing', 'Loa nén 35W', 0);
