package poscs.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import poscs.model.CustomerLifecycleEvent;
import poscs.model.RelationshipRating;
import poscs.model.User;

/**
 * DAO cho bảng customer_lifecycle_events -- lịch sử các lần đánh giá/thay
 * đổi xếp hạng quan hệ của khách hàng, cả tự động (CustomerEvaluator) lẫn
 * ghi nhận thủ công sau này.
 */
public class CustomerLifecycleEventDAO {

    /** Ghi 1 sự kiện mới. Trả về event_id vừa tạo, hoặc -1 nếu thất bại. */
    public int insert(CustomerLifecycleEvent event) {
        String sql = "INSERT INTO customer_lifecycle_events " +
                "(enterprise_id, event_type, relationship_rating, is_auto_generated, description, event_date, recorded_by) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection conn = DBContext.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, event.getEnterpriseId());
            ps.setString(2, event.getEventType());
            ps.setString(3, event.getRelationshipRating().getDbValue());
            ps.setBoolean(4, event.isAutoGenerated());
            ps.setString(5, event.getDescription());
            ps.setDate(6, event.getEventDate());
            ps.setInt(7, event.getRecordedBy());

            int affected = ps.executeUpdate();
            if (affected == 0) {
                return -1;
            }
            try (ResultSet keys = ps.getGeneratedKeys()) {
                return keys.next() ? keys.getInt(1) : -1;
            }
        } catch (SQLException ex) {
            System.err.println("--- LOI GHI LICH SU DANH GIA KHACH HANG ---");
            ex.printStackTrace();
            return -1;
        }
    }

    /** Lịch sử đánh giá của 1 khách hàng, mới nhất trước, kèm tên người ghi nhận. */
    public List<CustomerLifecycleEvent> findByEnterpriseId(int enterpriseId) {
        List<CustomerLifecycleEvent> result = new ArrayList<>();
        String sql = "SELECT ev.event_id, ev.enterprise_id, ev.event_type, ev.relationship_rating, " +
                "       ev.is_auto_generated, ev.description, ev.event_date, ev.recorded_by, ev.created_at, " +
                "       u.last_name AS recorder_last_name, u.middle_name AS recorder_middle_name, " +
                "       u.first_name AS recorder_first_name " +
                "FROM customer_lifecycle_events ev " +
                "JOIN users u ON u.user_id = ev.recorded_by " +
                "WHERE ev.enterprise_id = ? " +
                "ORDER BY ev.event_date DESC, ev.event_id DESC";
        try (Connection conn = DBContext.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, enterpriseId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    CustomerLifecycleEvent ev = new CustomerLifecycleEvent();
                    ev.setEventId(rs.getInt("event_id"));
                    ev.setEnterpriseId(rs.getInt("enterprise_id"));
                    ev.setEventType(rs.getString("event_type"));
                    ev.setRelationshipRating(RelationshipRating.fromDbValue(rs.getString("relationship_rating")));
                    ev.setAutoGenerated(rs.getBoolean("is_auto_generated"));
                    ev.setDescription(rs.getString("description"));
                    ev.setEventDate(rs.getDate("event_date"));
                    ev.setRecordedBy(rs.getInt("recorded_by"));
                    ev.setCreatedAt(rs.getTimestamp("created_at"));

                    User recorder = new User();
                    recorder.setLastName(rs.getString("recorder_last_name"));
                    recorder.setMiddleName(rs.getString("recorder_middle_name"));
                    recorder.setFirstName(rs.getString("recorder_first_name"));
                    ev.setRecordedByUser(recorder);

                    result.add(ev);
                }
            }
        } catch (SQLException ex) {
            System.err.println("--- LOI DOC LICH SU DANH GIA KHACH HANG ---");
            ex.printStackTrace();
        }
        return result;
    }
}
