package poscs.model;

import java.sql.Date;
import java.sql.Timestamp;

public class CustomerLifecycleEvent {
    private int eventId;
    private int enterpriseId;
    private String eventType;
    private RelationshipRating relationshipRating;
    private boolean autoGenerated; // Ánh xạ với is_auto_generated (tinyint(1))
    private String description;
    private Date eventDate;

    // Thuộc tính lưu trữ ID khóa ngoại
    private int recordedBy;

    // Thuộc tính Object để chứa dữ liệu join từ bảng users
    private User recordedByUser;

    private Timestamp createdAt;

    // Constructor rỗng (Bắt buộc cho JavaBean)
    public CustomerLifecycleEvent() {
    }

    // Constructor có tham số
    public CustomerLifecycleEvent(int eventId, int enterpriseId, String eventType,
                                   RelationshipRating relationshipRating, boolean autoGenerated,
                                   String description, Date eventDate, int recordedBy,
                                   Timestamp createdAt) {
        this.eventId = eventId;
        this.enterpriseId = enterpriseId;
        this.eventType = eventType;
        this.relationshipRating = relationshipRating;
        this.autoGenerated = autoGenerated;
        this.description = description;
        this.eventDate = eventDate;
        this.recordedBy = recordedBy;
        this.createdAt = createdAt;
    }

    // Các hàm Getters và Setters
    public int getEventId() { return eventId; }
    public void setEventId(int eventId) { this.eventId = eventId; }

    public int getEnterpriseId() { return enterpriseId; }
    public void setEnterpriseId(int enterpriseId) { this.enterpriseId = enterpriseId; }

    public String getEventType() { return eventType; }
    public void setEventType(String eventType) { this.eventType = eventType; }

    public RelationshipRating getRelationshipRating() { return relationshipRating; }
    public void setRelationshipRating(RelationshipRating relationshipRating) { this.relationshipRating = relationshipRating; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public Date getEventDate() { return eventDate; }
    public void setEventDate(Date eventDate) { this.eventDate = eventDate; }

    public int getRecordedBy() { return recordedBy; }
    public void setRecordedBy(int recordedBy) { this.recordedBy = recordedBy; }

    public User getRecordedByUser() { return recordedByUser; }
    public void setRecordedByUser(User recordedByUser) { this.recordedByUser = recordedByUser; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "CustomerLifecycleEvent{" + "eventId=" + eventId + ", enterpriseId=" + enterpriseId
                + ", relationshipRating=" + relationshipRating + ", eventDate=" + eventDate + '}';
    }
}
