package poscs.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.Test;
import org.mockito.MockedStatic;
import poscs.model.CustomerLifecycleEvent;
import poscs.model.RelationshipRating;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import static poscs.dao.JdbcStub.*;

/**
 * Test cho CustomerLifecycleEventDAO -- lịch sử đánh giá xếp hạng quan hệ
 * khách hàng. Điểm đáng chú ý là xếp hạng đi qua enum {@link RelationshipRating}
 * ở cả hai chiều: ghi xuống bằng {@code getDbValue()}, đọc lên bằng
 * {@code fromDbValue()}. Lệch một chiều là lịch sử đánh giá hiển thị sai hạng.
 *
 * Xem {@link JdbcStub} để biết những test này KHÔNG kiểm chứng gì (SQL, tên
 * cột, schema). JUnit 4 -- xem CustomerControllerTest.
 */
public class CustomerLifecycleEventDAOTest {

    private final CustomerLifecycleEventDAO dao = new CustomerLifecycleEventDAO();

    private static CustomerLifecycleEvent event() {
        CustomerLifecycleEvent e = new CustomerLifecycleEvent();
        e.setEnterpriseId(3);
        e.setEventType("Đánh giá định kỳ");
        e.setRelationshipRating(RelationshipRating.values()[0]);
        e.setAutoGenerated(false);
        e.setDescription("Khách hàng hợp tác tốt");
        e.setEventDate(Date.valueOf("2026-09-09"));
        e.setRecordedBy(5);
        return e;
    }

    // ------------------------------------------------------------------
    // insert
    // ------------------------------------------------------------------

    @Test
    public void insert_returnsGeneratedEventId() throws Exception {
        ResultSet keys = singleRow(row("id", 31));
        PreparedStatement ps = mock(PreparedStatement.class);
        when(ps.executeUpdate()).thenReturn(1);
        when(ps.getGeneratedKeys()).thenReturn(keys);
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            assertEquals(31, dao.insert(event()));
            verify(ps).setInt(1, 3);
            verify(ps).setInt(7, 5);
        }
    }

    @Test
    public void insert_writesRatingAsItsDbValueNotEnumName() throws Exception {
        ResultSet keys = singleRow(row("id", 31));
        PreparedStatement ps = mock(PreparedStatement.class);
        when(ps.executeUpdate()).thenReturn(1);
        when(ps.getGeneratedKeys()).thenReturn(keys);
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            RelationshipRating rating = RelationshipRating.values()[0];
            CustomerLifecycleEvent e = event();
            e.setRelationshipRating(rating);
            dao.insert(e);

            // Ghi enum.name() sẽ tạo giá trị mà fromDbValue() không đọc ngược được.
            verify(ps).setString(3, rating.getDbValue());
        }
    }

    @Test
    public void insert_noRowAffected_returnsMinusOne() throws Exception {
        PreparedStatement ps = mock(PreparedStatement.class);
        when(ps.executeUpdate()).thenReturn(0);
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            assertEquals(-1, dao.insert(event()));
        }
    }

    @Test
    public void insert_noGeneratedKey_returnsMinusOne() throws Exception {
        ResultSet emptyKeys = emptyResultSet();
        PreparedStatement ps = mock(PreparedStatement.class);
        when(ps.executeUpdate()).thenReturn(1);
        when(ps.getGeneratedKeys()).thenReturn(emptyKeys);
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            assertEquals(-1, dao.insert(event()));
        }
    }

    @Test
    public void insert_sqlError_returnsMinusOne() throws Exception {
        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenThrow(new SQLException("hỏng"));

            assertEquals(-1, dao.insert(event()));
        }
    }

    // ------------------------------------------------------------------
    // findByEnterpriseId
    // ------------------------------------------------------------------

    @Test
    public void findByEnterpriseId_mapsEventAndRecorderName() throws Exception {
        RelationshipRating rating = RelationshipRating.values()[0];
        List<Map<String, Object>> rows = new ArrayList<>();
        rows.add(row(
                "event_id", 31,
                "enterprise_id", 3,
                "event_type", "Đánh giá định kỳ",
                "relationship_rating", rating.getDbValue(),
                "is_auto_generated", 0,
                "description", "Khách hàng hợp tác tốt",
                "event_date", Date.valueOf("2026-09-09"),
                "recorded_by", 5,
                "created_at", null,
                "recorder_last_name", "Nguyễn",
                "recorder_middle_name", "Văn",
                "recorder_first_name", "An"));
        PreparedStatement ps = statementReturning(resultSetOf(rows));
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            List<CustomerLifecycleEvent> found = dao.findByEnterpriseId(3);

            assertEquals(1, found.size());
            CustomerLifecycleEvent e = found.get(0);
            assertEquals(31, e.getEventId());
            assertEquals("Đánh giá định kỳ", e.getEventType());
            // Chiều đọc ngược của enum phải khớp chiều ghi ở insert().
            assertEquals(rating, e.getRelationshipRating());
            assertFalse(e.isAutoGenerated());
            assertNotNull("Tên người ghi nhận hiển thị trên timeline", e.getRecordedByUser());
            assertEquals("Nguyễn", e.getRecordedByUser().getLastName());
            assertEquals("An", e.getRecordedByUser().getFirstName());
            verify(ps).setInt(1, 3);
        }
    }

    @Test
    public void findByEnterpriseId_noHistory_returnsEmptyList() throws Exception {
        PreparedStatement ps = statementReturning(emptyResultSet());
        Connection conn = connectionReturning(ps);

        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenReturn(conn);

            assertTrue(dao.findByEnterpriseId(3).isEmpty());
        }
    }

    @Test
    public void findByEnterpriseId_sqlError_returnsEmptyListNotNull() throws Exception {
        try (MockedStatic<DBContext> db = mockStatic(DBContext.class)) {
            db.when(DBContext::getConnection).thenThrow(new SQLException("hỏng"));

            List<CustomerLifecycleEvent> found = dao.findByEnterpriseId(3);

            // viewcustomerdetail.jsp lặp thẳng trên danh sách này.
            assertNotNull(found);
            assertTrue(found.isEmpty());
        }
    }
}
